<a href="https://colab.research.google.com/github/mochamadprayitno22-commits/data-project-agus-bigquery-telco-churn/blob/main/WHERE_CASE__WHEN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a id="A"></a>
# <b>A. <span style='color:#0B2F9F'><code>WHERE</code></span></b>

Klausa `WHERE` dalam SQL digunakan untuk menyaring baris data dalam query berdasarkan kondisi tertentu. Cara ini digunakan untuk menentukan kriteria yang harus dipenuhi agar baris data muncul dalam hasil query. Perintah `WHERE` dapat digunakan untuk menyaring nilai :

<ul>
<li>Berdasarkan Kondisi Tertentu</li>
<li>Berdasarkan Beberapa Kondisi</li>
<li>Menggunakan Pola Pencocokan</li>
<li>Menggunakan Rentang Nilai</li>
<li>Berdasarkan Kumpulan Nilai</li>
<li>Berdasarkan Nilai Null</li>
</ul>

In [1]:
!pip install pandasql
import pandas as pd
import pandasql as ps

# Membaca file yang sudah Anda upload
telco_services = pd.read_csv('/content/telco_services.csv')
population = pd.read_csv('/content/population.csv')
customer_status = pd.read_csv('/content/customer_status.csv')
customer_location = pd.read_csv('/content/customer_location.csv')
customer_demography = pd.read_csv('/content/customer_demography.csv')

Collecting pandasql
  Downloading pandasql-0.7.3.tar.gz (26 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.2.2)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.0.49)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2026.1)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy->pandasql) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy->pandasql) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.17.0)
Building wheels for collected packages: pandasql
  Building wheel for pandasql (setup.py) ... done
  Created wheel for pandasql: filename=pandasql-0.7.3-py3-none-any.whl size=26773 sha256=4d810f31e5993ee1e659cec58094c1b8d0c3ee9ce7b6ac761da7273a9c3f5400
  Stored in directory: /root/.cache/pip/wheels/15/a1/e7/6f92f295b5272ae5c02365e6b8fa19cb93f16a537090a1cf27
Successfully built pandasql
Installing collected packages: pandasql
Successfully installed pandasql-0.7.3

<a id="A.1."></a>
## <b>A.1. <span style='color:#0B2F9F'>Menyaring Nilai Berdasarkan Kondisi Tertentu</span></b>

Untuk melakukan penyaringan nilai berdasarkan kondisi tertentu dapat menggunakan <b>Comparison Operators</b>. Operator perbandingan (<i>comparison operators</i>) dalam SQL digunakan untuk membandingkan nilai-nilai dan menentukan bagaimana data memenuhi kondisi tertentu. Operator pembanding pada SQL disimbolkan dengan beberapa tanda berikut
<br><br>
<table border="1">
    <tr>
        <th>Tanda</th>
        <th>Deskripsi</th>
        <th>Contoh</th>
    </tr>
    <tr>
        <td>=</td>
        <td>Sama dengan (<i>Equals</i>)</td>
        <td>A = B</td>
    </tr>
    <tr>
        <td><></td>
        <td>Tidak Sama dengan (<i>Not Equals</i>)</td>
        <td>A <> B</td>
    </tr>
    <tr>
        <td><</td>
        <td>Kurang dari (<i>Less than</i>)</td>
        <td>A < B</td>
    </tr>
    <tr>
        <td>></td>
        <td>Lebih dari (<i>More than</i>)</td>
        <td>A > B</td>
    </tr>
    <tr>
        <td><=</td>
        <td>Kurang dari sama dengan (<i>Less than or Equals To</i>)</td>
        <td>A <= B</td>
    </tr>
    <tr>
        <td>>=</td>
        <td>Lebih dari sama dengan (<i>More than or Equals To</i>)</td>
        <td>A >= B</td>
    </tr>
</table>

#### <i><b><span style='color:#55679C'>Quest</span> : Tampilkan semua data pada tabel customer_services yang menggunakan layanan telfon (phone_services)!</b></i>

In [2]:
ps.sqldf("SELECT * FROM telco_services WHERE phone_service = 'Yes'")

,customer_id,referred_a_friend,number_of_referrals,tenure_in_months,offer,phone_service,avg_monthly_long_distance_charges,multiple_lines,internet_service,internet_type,...,unlimited_data,contract,paperless_billing,payment_method,monthly_charge,total_charges,total_refunds,total_extra_data_charges,total_long_distance_charges,total_revenue
0,7495-OOKFY,Yes,1,8,Offer E,Yes,48.85,Yes,Yes,Fiber Optic,...,Yes,Month-to-Month,Yes,Credit Card,80.65,633.30,0.00,0,390.80,1024.10
1,1658-BYGOY,No,0,18,Offer D,Yes,11.33,Yes,Yes,Fiber Optic,...,Yes,Month-to-Month,Yes,Bank Withdrawal,95.45,1752.55,45.61,0,203.94,1910.88
2,4598-XLKNJ,Yes,1,25,Offer C,Yes,19.76,No,Yes,Fiber Optic,...,Yes,Month-to-Month,Yes,Bank Withdrawal,98.50,2514.50,13.43,0,494.00,2995.07
3,4846-WHAFZ,Yes,1,37,Offer C,Yes,6.33,Yes,Yes,Fiber Optic,...,Yes,Month-to-Month,Yes,Bank Withdrawal,76.50,2868.15,0.00,0,234.21,3102.36
4,4412-YLTKF,No,0,27,Offer C,Yes,3.33,Yes,Yes,Fiber Optic,...,No,Month-to-Month,Yes,Bank Withdrawal,78.05,2135.50,0.00,10,89.91,2235.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6356,8456-QDAVC,No,0,19,None,Yes,29.55,No,Yes,Fiber Optic,...,Yes,Month-to-Month,Yes,Bank Withdrawal,78.70,1495.10,26.84,0,561.45,2029.71
6357,2569-WGERO,No,0,72,None,Yes,22.77,No,No,None,...,No,Two Year,Yes,Bank Withdrawal,21.15,1419.40,19.31,0,1639.44,3039.53
6358,6840-RESVB,Yes,1,24,Offer C,Yes,36.05,Yes,Yes,Cable,...,Yes,One Year,Yes,Mailed Check,84.80,1990.50,48.23,0,865.20,2807.47
6359,2234-XADUH,Yes,4,72,None,Yes,29.66,Yes,Yes,Fiber Optic,...,Yes,One Year,Yes,Credit Card,103.20,7362.90,45.38,0,2135.52,9453.04
6360,3186-AJIEK,No,0,66,None,Yes,30.96,No,Yes,Fiber Optic,...,Yes,Two Year,Yes,Bank Withdrawal,105.65,6844.50,0.00,0,2043.36,8887.86

#### <i><b><span style='color:#55679C'>Quest</span> : Tampilkan semua data pada tabel customer_services yang tenure_in_monthsnya lebih dari 30!</b></i>

In [3]:
ps.sqldf("SELECT * FROM telco_services WHERE tenure_in_months > 30")

,customer_id,referred_a_friend,number_of_referrals,tenure_in_months,offer,phone_service,avg_monthly_long_distance_charges,multiple_lines,internet_service,internet_type,...,unlimited_data,contract,paperless_billing,payment_method,monthly_charge,total_charges,total_refunds,total_extra_data_charges,total_long_distance_charges,total_revenue
0,4846-WHAFZ,Yes,1,37,Offer C,Yes,6.33,Yes,Yes,Fiber Optic,...,Yes,Month-to-Month,Yes,Bank Withdrawal,76.50,2868.15,0.00,0,234.21,3102.36
1,3445-HXXGF,Yes,6,58,Offer B,No,0.00,No,Yes,DSL,...,Yes,Month-to-Month,Yes,Bank Withdrawal,45.30,2651.20,40.95,0,0.00,2610.25
2,0265-EDXBD,Yes,2,32,Offer C,Yes,47.34,Yes,Yes,Fiber Optic,...,Yes,Month-to-Month,Yes,Bank Withdrawal,74.90,2303.35,0.00,0,1514.88,3818.23
3,5020-ZSTTY,No,0,54,Offer B,Yes,12.08,Yes,Yes,DSL,...,Yes,One Year,No,Bank Withdrawal,82.45,4350.10,0.00,0,652.32,5002.42
4,0533-BNWKF,Yes,2,55,Offer B,Yes,42.82,Yes,Yes,Fiber Optic,...,No,Month-to-Month,Yes,Bank Withdrawal,85.45,4874.70,0.00,90,2355.10,7319.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3397,9281-CEDRU,Yes,2,68,None,Yes,8.62,No,Yes,DSL,...,Yes,Two Year,No,Bank Withdrawal,64.10,4326.25,19.12,0,586.16,4893.29
3398,9767-FFLEM,No,0,38,None,Yes,35.04,No,Yes,Fiber Optic,...,Yes,Month-to-Month,Yes,Credit Card,69.50,2625.25,20.19,0,1331.52,3936.58
3399,2569-WGERO,No,0,72,None,Yes,22.77,No,No,None,...,No,Two Year,Yes,Bank Withdrawal,21.15,1419.40,19.31,0,1639.44,3039.53
3400,2234-XADUH,Yes,4,72,None,Yes,29.66,Yes,Yes,Fiber Optic,...,Yes,One Year,Yes,Credit Card,103.20,7362.90,45.38,0,2135.52,9453.04
3401,3186-AJIEK,No,0,66,None,Yes,30.96,No,Yes,Fiber Optic,...,Yes,Two Year,Yes,Bank Withdrawal,105.65,6844.50,0.00,0,2043.36,8887.86

#### <i><b><span style='color:#55679C'>Quest</span> : Tampilkan kolom customer_id, tenure_in_months, internet_type pada tabel customer_services yang internet_type nya menggunakan Fiber Optic!</b></i>

In [4]:
ps.sqldf("SELECT * FROM telco_services WHERE internet_type = 'Fiber Optic' AND number_of_referrals > 1")

,customer_id,referred_a_friend,number_of_referrals,tenure_in_months,offer,phone_service,avg_monthly_long_distance_charges,multiple_lines,internet_service,internet_type,...,unlimited_data,contract,paperless_billing,payment_method,monthly_charge,total_charges,total_refunds,total_extra_data_charges,total_long_distance_charges,total_revenue
0,0265-EDXBD,Yes,2,32,Offer C,Yes,47.34,Yes,Yes,Fiber Optic,...,Yes,Month-to-Month,Yes,Bank Withdrawal,74.90,2303.35,0.00,0,1514.88,3818.23
1,0533-BNWKF,Yes,2,55,Offer B,Yes,42.82,Yes,Yes,Fiber Optic,...,No,Month-to-Month,Yes,Bank Withdrawal,85.45,4874.70,0.00,90,2355.10,7319.80
2,5956-VKDTT,Yes,4,5,Offer E,Yes,45.76,Yes,Yes,Fiber Optic,...,Yes,Month-to-Month,Yes,Bank Withdrawal,74.35,334.80,0.00,0,228.80,563.60
3,3419-SNJJD,Yes,3,65,Offer B,Yes,18.39,Yes,Yes,Fiber Optic,...,Yes,Month-to-Month,No,Bank Withdrawal,105.25,6786.40,0.00,0,1195.35,7981.75
4,4554-YGZIH,Yes,3,49,Offer B,Yes,22.92,Yes,Yes,Fiber Optic,...,Yes,Month-to-Month,No,Credit Card,90.05,4547.25,0.00,0,1123.08,5670.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
807,9547-ITEFG,Yes,8,9,Offer E,Yes,23.42,Yes,Yes,Fiber Optic,...,Yes,Month-to-Month,Yes,Credit Card,102.60,897.75,0.00,0,210.78,1108.53
808,0376-OIWME,Yes,3,36,Offer C,Yes,41.33,No,Yes,Fiber Optic,...,Yes,Month-to-Month,Yes,Bank Withdrawal,93.60,3366.05,16.56,0,1487.88,4837.37
809,9586-JGQKH,Yes,8,64,Offer B,Yes,49.26,Yes,Yes,Fiber Optic,...,Yes,Two Year,Yes,Bank Withdrawal,105.40,6794.75,32.24,0,3152.64,9915.15
810,7398-LXGYX,Yes,2,44,Offer B,Yes,21.39,Yes,Yes,Fiber Optic,...,Yes,Month-to-Month,Yes,Credit Card,84.80,3626.35,43.96,0,941.16,4523.55
811,2234-XADUH,Yes,4,72,None,Yes,29.66,Yes,Yes,Fiber Optic,...,Yes,One Year,Yes,Credit Card,103.20,7362.90,45.38,0,2135.52,9453.04

<a id="A.2."></a>
## <b>A.2. <span style='color:#0B2F9F'>Menyaring Nilai Berdasarkan Beberapa Kondisi</span></b>

Untuk melakukan penyaringan nilai berdasarkan beberapa kondisi dapat menggunakan <b>Logical Operators</b>. Operator logika (<i>logical operator</i>) adalah simbol atau kata kunci yang digunakan untuk menghubungkan dua atau lebih ekspresi logis dan menghasilkan nilai logis baru berdasarkan operasi tersebut. Operator logika pada SQL disimbolkan dengan beberapa tanda berikut
<br><br>
<table border="1">
    <tr>
        <th>Tanda</th>
        <th>Deskripsi</th>
        <th>Kondisi</th>
        <th>Contoh</th>
    </tr>
    <tr>
        <td><b>AND</b></td>
        <td>Operator penghubung 'DAN'</td>
        <td><i>Statement</i> bernilai benar jika keduanya benar / terpenuhi,<br>jika tidak demikian maka bernilai salah</td>
        <td>Condition 1 <b>AND</b> Condition 2</td>
    </tr>
    <tr>
        <td><b>OR</b></td>
        <td>Operator penghubung 'ATAU'</td>
        <td><i>Statement</i> bernilai salah jika keduanya salah / tidak terpenuhi,<br>jika tidak demikian maka bernilai benar</td>
        <td>Condition 1 <b>OR</b> Condition 2</td>
    </tr>
    <tr>
        <td><b>NOT</b></td>
        <td>Operator 'BUKAN'</td>
        <td>Operator ini membalikkan nilai logis dari ekspresi yang dioperasikan</td>
        <td><b>NOT</b> Condition 1</td>
    </tr>
</table>
<br><br>
Saat digunakan, untuk menyaring dua atau lebih pernyataan dengan operator logika akan berlaku kriteria sebagai berikut
<br><br>
<table border="1">
    <tr>
        <th>Condition 1</th>
        <th>Condition 2</th>
        <th>Condition 1 <span style='color:#55679C'>AND</span> Condition 2</th>
        <th>Condition 1 <span style='color:#55679C'>OR</span> Condition 2</th>
    </tr>
    <tr>
        <td align = "center"><span style='color:#EEF296'>Benar</span></td>
        <td align = "center"><span style='color:#EEF296'>Benar</span></td>
        <td align = "center"><span style='color:#EEF296'>Benar</span></td>
        <td align = "center"><span style='color:#EEF296'>Benar</span></td>
    </tr>
    <tr>
        <td align = "center"><span style='color:#EEF296'>Benar</span></td>
        <td align = "center"><span style='color:#508D69'>Salah</span></td>
        <td align = "center"><span style='color:#508D69'>Salah</span></td>
        <td align = "center"><span style='color:#EEF296'>Benar</span></td>
    </tr>
    <tr>
        <td align = "center"><span style='color:#508D69'>Salah</span></td>
        <td align = "center"><span style='color:#EEF296'>Benar</span></td>
        <td align = "center"><span style='color:#508D69'>Salah</span></td>
        <td align = "center"><span style='color:#EEF296'>Benar</span></td>
    </tr>
    <tr>
        <td align = "center"><span style='color:#508D69'>Salah</span></td>
        <td align = "center"><span style='color:#508D69'>Salah</span></td>
        <td align = "center"><span style='color:#508D69'>Salah</span></td>
        <td align = "center"><span style='color:#508D69'>Salah</span></td>
    </tr>
</table>

Saat query dijalankan, hanya output yang bernilai benar saja yang akan ditampilkan.

#### <i><b><span style='color:#55679C'>Quest</span> : Tampilkan semua pada tabel customer_services yang mereferensikan layanan kepada orang lain dengan jumlah referal lebih dari 1!</b></i>

In [6]:
ps.sqldf("SELECT * FROM telco_services WHERE internet_type = 'Fiber Optic' AND number_of_referrals > 1")

,customer_id,referred_a_friend,number_of_referrals,tenure_in_months,offer,phone_service,avg_monthly_long_distance_charges,multiple_lines,internet_service,internet_type,...,unlimited_data,contract,paperless_billing,payment_method,monthly_charge,total_charges,total_refunds,total_extra_data_charges,total_long_distance_charges,total_revenue
0,0265-EDXBD,Yes,2,32,Offer C,Yes,47.34,Yes,Yes,Fiber Optic,...,Yes,Month-to-Month,Yes,Bank Withdrawal,74.90,2303.35,0.00,0,1514.88,3818.23
1,0533-BNWKF,Yes,2,55,Offer B,Yes,42.82,Yes,Yes,Fiber Optic,...,No,Month-to-Month,Yes,Bank Withdrawal,85.45,4874.70,0.00,90,2355.10,7319.80
2,5956-VKDTT,Yes,4,5,Offer E,Yes,45.76,Yes,Yes,Fiber Optic,...,Yes,Month-to-Month,Yes,Bank Withdrawal,74.35,334.80,0.00,0,228.80,563.60
3,3419-SNJJD,Yes,3,65,Offer B,Yes,18.39,Yes,Yes,Fiber Optic,...,Yes,Month-to-Month,No,Bank Withdrawal,105.25,6786.40,0.00,0,1195.35,7981.75
4,4554-YGZIH,Yes,3,49,Offer B,Yes,22.92,Yes,Yes,Fiber Optic,...,Yes,Month-to-Month,No,Credit Card,90.05,4547.25,0.00,0,1123.08,5670.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
807,9547-ITEFG,Yes,8,9,Offer E,Yes,23.42,Yes,Yes,Fiber Optic,...,Yes,Month-to-Month,Yes,Credit Card,102.60,897.75,0.00,0,210.78,1108.53
808,0376-OIWME,Yes,3,36,Offer C,Yes,41.33,No,Yes,Fiber Optic,...,Yes,Month-to-Month,Yes,Bank Withdrawal,93.60,3366.05,16.56,0,1487.88,4837.37
809,9586-JGQKH,Yes,8,64,Offer B,Yes,49.26,Yes,Yes,Fiber Optic,...,Yes,Two Year,Yes,Bank Withdrawal,105.40,6794.75,32.24,0,3152.64,9915.15
810,7398-LXGYX,Yes,2,44,Offer B,Yes,21.39,Yes,Yes,Fiber Optic,...,Yes,Month-to-Month,Yes,Credit Card,84.80,3626.35,43.96,0,941.16,4523.55
811,2234-XADUH,Yes,4,72,None,Yes,29.66,Yes,Yes,Fiber Optic,...,Yes,One Year,Yes,Credit Card,103.20,7362.90,45.38,0,2135.52,9453.04

#### <i><b><span style='color:#55679C'>Quest</span> : Tampilkan kolom customer_id, tenure_in_months, internet_type dan total_revenue pada tabel customer_services yang internet_type nya menggunakan Fiber Optic atau tenure_in_months kurang dari sama dengan 30!</b></i>

In [7]:
ps.sqldf("SELECT * FROM telco_services WHERE tenure_in_months > 30")

,customer_id,referred_a_friend,number_of_referrals,tenure_in_months,offer,phone_service,avg_monthly_long_distance_charges,multiple_lines,internet_service,internet_type,...,unlimited_data,contract,paperless_billing,payment_method,monthly_charge,total_charges,total_refunds,total_extra_data_charges,total_long_distance_charges,total_revenue
0,4846-WHAFZ,Yes,1,37,Offer C,Yes,6.33,Yes,Yes,Fiber Optic,...,Yes,Month-to-Month,Yes,Bank Withdrawal,76.50,2868.15,0.00,0,234.21,3102.36
1,3445-HXXGF,Yes,6,58,Offer B,No,0.00,No,Yes,DSL,...,Yes,Month-to-Month,Yes,Bank Withdrawal,45.30,2651.20,40.95,0,0.00,2610.25
2,0265-EDXBD,Yes,2,32,Offer C,Yes,47.34,Yes,Yes,Fiber Optic,...,Yes,Month-to-Month,Yes,Bank Withdrawal,74.90,2303.35,0.00,0,1514.88,3818.23
3,5020-ZSTTY,No,0,54,Offer B,Yes,12.08,Yes,Yes,DSL,...,Yes,One Year,No,Bank Withdrawal,82.45,4350.10,0.00,0,652.32,5002.42
4,0533-BNWKF,Yes,2,55,Offer B,Yes,42.82,Yes,Yes,Fiber Optic,...,No,Month-to-Month,Yes,Bank Withdrawal,85.45,4874.70,0.00,90,2355.10,7319.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3397,9281-CEDRU,Yes,2,68,None,Yes,8.62,No,Yes,DSL,...,Yes,Two Year,No,Bank Withdrawal,64.10,4326.25,19.12,0,586.16,4893.29
3398,9767-FFLEM,No,0,38,None,Yes,35.04,No,Yes,Fiber Optic,...,Yes,Month-to-Month,Yes,Credit Card,69.50,2625.25,20.19,0,1331.52,3936.58
3399,2569-WGERO,No,0,72,None,Yes,22.77,No,No,None,...,No,Two Year,Yes,Bank Withdrawal,21.15,1419.40,19.31,0,1639.44,3039.53
3400,2234-XADUH,Yes,4,72,None,Yes,29.66,Yes,Yes,Fiber Optic,...,Yes,One Year,Yes,Credit Card,103.20,7362.90,45.38,0,2135.52,9453.04
3401,3186-AJIEK,No,0,66,None,Yes,30.96,No,Yes,Fiber Optic,...,Yes,Two Year,Yes,Bank Withdrawal,105.65,6844.50,0.00,0,2043.36,8887.86

#### <i><b><span style='color:#55679C'>Quest</span> : Tampilkan kolom customer_id, internet_type dan total_revenue pada tabel customer_services yang internet_type nya bukan menggunakan Fiber Optic, lalu urutkan berdasarkan total_revenue mulai dari yang paling besar!</b></i>

In [8]:
# Quest: Internet bukan Fiber Optic, urutkan revenue terbesar
ps.sqldf("""
SELECT
    customer_id,
    internet_type,
    total_revenue
FROM telco_services
WHERE internet_type != 'Fiber Optic'
ORDER BY total_revenue DESC
""")

     customer_id internet_type  total_revenue
0     7503-MIOGA         Cable       10190.07
1     3569-JFODW           DSL        9939.97
2     2990-IAJSV         Cable        9902.27
3     7579-KKLOE           DSL        9893.23
4     9297-EONCV           DSL        9880.32
...          ...           ...            ...
2477  7365-BVCJH           DSL          24.40
2478  3439-GVUSX           DSL          24.40
2479  1334-FJSVR           DSL          24.25
2480  5351-QESIO         Cable          24.20
2481  3797-VTIDR           DSL          23.45

[2482 rows x 3 columns]

<a id="A.3."></a>
## <b>A.3. <span style='color:#0B2F9F'>Menyaring Nilai Menggunakan Pola Pencocokan</span></b>

SQL telah mendukung operator dan fungsi yang memungkinkan untuk melakukan pencocokan pola pada sebuah teks. Untuk melakukan hal ini dapat menggunakan query `LIKE` dengan bantuan tanda <b>Wildcard (%)</b>. Tanda <b>Wildcard (%)</b>. Wildcard memungkinkan untuk mencari data dengan pola yang tidak pasti atau variatif pada sebuah teks. Contoh :

Sebuah data karyawan memiliki kolom nama, terdapat nama Ilham, Kurnia, Bachtiyar, Baim, Ridho dan Deki
<ul>
    <li>Untuk mencari nama yang diawali huruf B, gunakan sintaks <code>WHERE nama LIKE 'B%'</code>.<br>Nama yang cocok : Bachtiyar & Baim</li><br>
    <li>Untuk mencari nama yang diakhiri dengan huruf m, gunakan sintaks <code>WHERE nama LIKE '%m'</code>.<br>Nama yang cocok : Ilham & Baim</li><br>
    <li>Untuk mencari nama yang diawali huruf B namun diakhiri dengan m, gunakan sintaks <code>WHERE nama LIKE 'B%m'</code>.<br>Nama yang cocok : Baim</li>
</ul>

#### <i><b><span style='color:#55679C'>Quest</span> : Tampilkan 5 data customer_id pada tabel customer_service yang nomor kodenya dimulai angka 2 dan urutkan dari yang terkecil hingga terbesar!</b></i>

In [9]:
ps.sqldf("SELECT customer_id FROM telco_services WHERE customer_id LIKE '2%' ORDER BY customer_id ASC LIMIT 5")

  customer_id
0  2000-DHJUY
1  2000-MPKCA
2  2001-EWBQU
3  2001-MCUUW
4  2002-MZHWP

<a id="A.4."></a>
## <b>A.4. <span style='color:#0B2F9F'>Menyaring Nilai Menggunakan Rentang Nilai</span></b>

Selain menggunakan operator pembanding, dapat juga menggunakan query `BETWEEN` untuk mendapatkan nilai pada rentang tertentu. Untuk menyingkat penulisan <code>nilai1 <= nama_kolom AND nama_kolom <= nilai2</code> dapat menggunakan alternatif <code>nama_kolom BETWEEN nilai1 AND nilai2</code>.

#### <i><b><span style='color:#55679C'>Quest</span> : Tampilkan data customer_id, internet_type, avg_monthly_gb_download pada tabel customer_service yang avg_monthly_gb_download berada pada rentang nilai 20 hingga 30!</b></i>

In [10]:
ps.sqldf("SELECT customer_id, internet_type, avg_monthly_gb_download FROM telco_services WHERE avg_monthly_gb_download BETWEEN 20 AND 30")

     customer_id internet_type  avg_monthly_gb_download
0     0390-DCFDQ   Fiber Optic                       30
1     3445-HXXGF           DSL                       24
2     0094-OIFMO   Fiber Optic                       29
3     9947-OTFQU   Fiber Optic                       29
4     7273-TEFQD           DSL                       28
...          ...           ...                      ...
1814  1685-BQULA   Fiber Optic                       22
1815  1471-GIQKQ           DSL                       27
1816  0550-DCXLH           DSL                       21
1817  7750-EYXWZ         Cable                       24
1818  6840-RESVB         Cable                       24

[1819 rows x 3 columns]

<a id="A.5."></a>
## <b>A.5. <span style='color:#0B2F9F'>Menyaring Nilai Berdasarkan Kumpulan Nilai</span></b>

Untuk melakukan penyaringan nilai berdasarkan kumpulan nilai dapat menggunakan <b>Operator Keanggotaan</b>. Operator keanggotaan (<i>membership operators</i>) dalam SQL digunakan untuk digunakan untuk memeriksa apakah suatu nilai cocok dengan nilai apa pun dalam daftar atau subkueri tertentu. Contoh penggunaan operator keanggotaan pada SQL adalah sebagai berikut :

Sebuah data karyawan memiliki kolom nama, terdapat nama Ilham, Kurnia, Bachtiyar, Baim, Ridho dan Deki
<ul>
    <li>Untuk mencari nama Ilham dan Ridho, gunakan sintaks <code>WHERE nama IN ('Ilham', 'Ridho')</code>.<br>Output : Ilham, Ridho</li><br>
    <li>Untuk mencari nama <b>SELAIN</b> Ilham dan Ridho, gunakan sintaks <code>WHERE nama NOT IN ('Ilham', 'Ridho')</code>.<br>Output : Kurnia, Bachtiyar, Baim, Deki</li>
</ul>

#### <i><b><span style='color:#55679C'>Quest</span> : Tampilkan data customer_id, offer dan total_revenue pada tabel customer_service yang tipe penawaran-nya adalah A & E!</b></i>

In [11]:
ps.sqldf("SELECT customer_id, offer, total_revenue FROM telco_services WHERE offer IN ('Offer A', 'Offer E')")

     customer_id    offer  total_revenue
0     7495-OOKFY  Offer E        1024.10
1     0390-DCFDQ  Offer E          85.73
2     2070-FNEXE  Offer E         681.20
3     9514-JDSKI  Offer E          40.20
4     7273-TEFQD  Offer E         132.20
...          ...      ...            ...
1320  5351-QESIO  Offer E          24.20
1321  5568-DMXZS  Offer E         853.41
1322  8468-FZTOE  Offer A        6526.52
1323  0218-QNVAS  Offer A        9108.90
1324  0871-OPBXW  Offer E          52.95

[1325 rows x 3 columns]

#### <i><b><span style='color:#55679C'>Quest</span> : Tampilkan data customer_id, offer, internet_type dan total_revenue pada tabel customer_service yang tipe penawaran-nya adalah A & E namun internet_type-nya bukan Fiber Optic atau DSL!</b></i>

In [12]:
ps.sqldf("""
SELECT
    customer_id,
    offer,
    internet_type,
    total_revenue
FROM telco_services
WHERE offer IN ('Offer A', 'Offer E')
  AND internet_type NOT IN ('Fiber Optic', 'DSL')
""")

    customer_id    offer internet_type  total_revenue
0    7206-GZCDC  Offer E         Cable          98.93
1    5047-LHVLY  Offer E         Cable          89.93
2    8080-DDEMJ  Offer E         Cable          60.38
3    2722-JMONI  Offer E         Cable          73.79
4    4201-JMNGR  Offer E         Cable          82.02
..          ...      ...           ...            ...
174  2314-TNDJQ  Offer A         Cable        3880.05
175  6439-PKTRR  Offer A         Cable        5905.65
176  5351-QESIO  Offer E         Cable          24.20
177  5568-DMXZS  Offer E         Cable         853.41
178  8468-FZTOE  Offer A         Cable        6526.52

[179 rows x 4 columns]

<a id="A.6."></a>
## <b>A.6. <span style='color:#0B2F9F'>Menyaring Nilai Berdasarkan Nilai NULL</span></b>

`NULL` adalah nilai khusus yang digunakan untuk menunjukkan bahwa data tidak tersedia, tidak diketahui, atau tidak relevan. Untuk mencari data yang NULL pada SQL gunakan perintah berikut :

<ul>
    <li>Untuk mencari data yang kosong atau NULL, gunakan sintaks <code>WHERE nama_kolom IS NULL</code></li><br>
    <li>Untuk mencari data yang tidak kosong atau NOT NULL, gunakan sintaks <code>WHERE nama_kolom IS NOT NULL</code></li><br>
</ul>

#### <i><b><span style='color:#55679C'>Quest</span> : Tampilkan data customer_id, offer, internet_type dan total_revenue pada tabel customer_service yang tidak mendapatkan tipe penawaran!</b></i>

In [13]:
ps.sqldf("""
SELECT
    customer_id,
    offer,
    internet_type,
    total_revenue
FROM telco_services
WHERE offer IS NULL
   OR offer = 'nan'
""")

     customer_id offer internet_type  total_revenue
0     8779-QRDMV  None           DSL          59.65
1     3488-PGMQJ  None   Fiber Optic         620.79
2     0623-IIHUG  None         Cable         840.10
3     9057-MSWCO  None         Cable         945.10
4     4895-TMWIR  None          None         539.69
...          ...   ...           ...            ...
3872  7750-EYXWZ  None         Cable         702.89
3873  2569-WGERO  None          None        3039.53
3874  2234-XADUH  None   Fiber Optic        9453.04
3875  4801-JZAZL  None           DSL         319.21
3876  3186-AJIEK  None   Fiber Optic        8887.86

[3877 rows x 4 columns]

<a id="B"></a>
# <b>B. <span style='color:#0B2F9F'><code>CASE-WHEN</code></b>

`CASE` adalah sebuah ekspresi dalam SQL yang digunakan untuk melakukan logika kondisional. `CASE` sering digunakan untuk mengubah nilai yang ditampilkan dalam query berdasarkan kondisi tertentu. Untuk dapat menggunakan perintah `CASE` gunakan sintaks umum berikut

SELECT<br>
    CASE<br>
        WHEN condition1 THEN result1<br>
        WHEN condition2 THEN result2<br>
        ...<br>
        ELSE default_result<br>
    END AS alias_name<br>
FROM table_name<br>

#### <i><b><span style='color:#55679C'>Quest</span> : Tampilkan kolom customer_id, monthly_charge dan monthly_charge_type pada tabel customer_service, dengan ketentuan</b></i><br>
<ul>
<li>Jika monthly_charge < 50.2 maka monthly_charge_type = 'Low Charge'</li>
<li>Jika 50.2 <= monthly_charge < 83.2 maka monthly_charge_type = 'Medium Charge'</li>
<li>Jika monthly_charge >= 83.2 50.2 maka monthly_charge_type = 'High Charge'</li>
</ul>

In [14]:
ps.sqldf("""
SELECT customer_id, monthly_charge,
    CASE
        WHEN monthly_charge < 50.2 THEN 'Low Charge'
        WHEN monthly_charge >= 50.2 AND monthly_charge < 83.2 THEN 'Medium Charge'
        ELSE 'High Charge'
    END AS monthly_charge_type
FROM telco_services
""")

     customer_id  monthly_charge monthly_charge_type
0     8779-QRDMV           39.65          Low Charge
1     7495-OOKFY           80.65       Medium Charge
2     1658-BYGOY           95.45         High Charge
3     4598-XLKNJ           98.50         High Charge
4     4846-WHAFZ           76.50       Medium Charge
...          ...             ...                 ...
7038  2569-WGERO           21.15          Low Charge
7039  6840-RESVB           84.80         High Charge
7040  2234-XADUH          103.20         High Charge
7041  4801-JZAZL           29.60          Low Charge
7042  3186-AJIEK          105.65         High Charge

[7043 rows x 3 columns]

#### <i><b><span style='color:#55679C'>Quest</span> : Tampilkan kolom customer_id, phone_service, internet_service dan phone_internet_type pada tabel customer_service, dengan ketentuan</b></i><br>
<ul>
<li>Jika customer menggunakan layanan Telepon & Internet, maka phone_internet_type = Phone & Internet</li>
<li>Jika customer menggunakan layanan Telepon namun tidak menggunakan layanan Internet, maka phone_internet_type = Phone Only</li>
<li>Jika customer tidak menggunakan layanan Telepon namun menggunakan layanan Internet, maka phone_internet_type = Internet Only</li>
<li>Jika customer tidak menggunakan kedua layanan tersebut, maka phone_internet_type = No Phone & Internet</li>
</ul>

In [15]:
ps.sqldf("""
SELECT customer_id, phone_service, internet_service,
    CASE
        WHEN phone_service = 'Yes' AND internet_service = 'Yes' THEN 'Phone & Internet'
        WHEN phone_service = 'Yes' AND internet_service = 'No' THEN 'Phone Only'
        WHEN phone_service = 'No' AND internet_service = 'Yes' THEN 'Internet Only'
        ELSE 'No Phone & Internet'
    END AS phone_internet_type
FROM telco_services
""")

     customer_id phone_service internet_service phone_internet_type
0     8779-QRDMV            No              Yes       Internet Only
1     7495-OOKFY           Yes              Yes    Phone & Internet
2     1658-BYGOY           Yes              Yes    Phone & Internet
3     4598-XLKNJ           Yes              Yes    Phone & Internet
4     4846-WHAFZ           Yes              Yes    Phone & Internet
...          ...           ...              ...                 ...
7038  2569-WGERO           Yes               No          Phone Only
7039  6840-RESVB           Yes              Yes    Phone & Internet
7040  2234-XADUH           Yes              Yes    Phone & Internet
7041  4801-JZAZL            No              Yes       Internet Only
7042  3186-AJIEK           Yes              Yes    Phone & Internet

[7043 rows x 4 columns]

Data Source : <i>https://www.ibm.com/docs/en/cognos-analytics/11.1.0?topic=samples-telco-customer-churn</i>

---